name: Docker Image CI

on:
  workflow_dispatch:
    
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./dj-docker/dockerdj/


    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: run command 
      run: docker build -t jap-djangoj .  /usr/bin/bash
     # run: docker push japanjot15/djangostart:japppppppppp
